import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/custom_compo/Footer";
import { NavbarDemo } from "@/custom_compo/Navbar";
import { Providers } from "@/redux/Provider";
import { Open_Sans, Roboto_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import AnimatedLayout from "./AnimatedLayout";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-opensans",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${robotoMono.variable} font-sans`}
      suppressHydrationWarning
    >
      <body>
        <Providers>
          <NavbarDemo />
          <AnimatedLayout>{children}</AnimatedLayout>
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
