import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/custom_compo/Footer";
import { NavbarDemo } from "@/custom_compo/Navbar";
import { ThemeProvider } from "@/custom_compo/theme-provider";



export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <NavbarDemo />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
