import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/custom_compo/Footer";
import { NavbarDemo } from "@/custom_compo/Navbar";
import { ThemeProvider } from "@/custom_compo/theme-provider";
import {Open_Sans,Roboto_Mono} from "next/font/google"

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans'
})

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})


export const metadata: Metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable} ${robotoMono.variable} font-sans`} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <NavbarDemo />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
